# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e2ed21ee5116e839b18cbd7ae16ccf1ab0456c4f07d690a975ae41a6a45c5833dc888f88f80d63ca6393908dba63bca67fec5040dab5d01a6c9cfed246515fe1

test:
  secret_key_base: 89eb95096c7562f4fbcde430cdcc5414e9d14c644a20cd6f9fad08e825ac6cb4dfad131783c645b99eda548d5043eb72a6b0b3daa8b82452bbb47d74d8a01e66

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
