#!/bin/sh

# script/server: Launch the application and any extra required processes locally with puma.
# script/server use-guard: Lunch application with Guard

set -e

cd "$(dirname "$0")/.."

# start dependencies
script/mysql

# ensure everything in the app is up to date.
script/update

test -z "$RACK_ENV" &&
  RACK_ENV='development'

# boot the app and any other necessary processes.
# To boot under unicorn use `script/server --use-unicorn`
if [[ $1 = "--use-unicorn" ]]; then
  bundle exec unicorn -c config/unicorn.local.rb
else
  bundle exec rails s -p 3000
fi
